#ifndef APNSROUTE_BINDING_STATUS_H
#define APNSROUTE_BINDING_STATUS_H
enum apr_binding_status { APR_BIND_NONE, APR_BIND_NATIVE, APR_BIND_ACCEPTED,
    APR_BIND_NO_TUNNEL, APR_BIND_AMBIGUOUS, APR_BIND_FAMILY, APR_BIND_SELECTION,
    APR_BIND_CONSTRAINT, APR_BIND_LOCAL, APR_BIND_ALLOCATION, APR_BIND_KERNEL,
    APR_BIND_CHANGED, APR_BIND_CAPACITY, APR_BIND_UNSUPPORTED_FLAGS, APR_BIND_INTERFACE_CHECK };
enum { APR_BIND_RESULT_READ=1, APR_BIND_RESULT_INVALID=2,
    APR_BIND_RESULT_INTERFACE=4, APR_BIND_RESULT_POLICY=8, APR_BIND_RESULT_MATCH=16,
    APR_BIND_RESULT_NEXUS=32 };
/* status | candidate count (saturates at 2) << 8 | candidate family mask << 16 */
#endif
