#ifndef APNSROUTE_CONNECTION_STATUS_H
#define APNSROUTE_CONNECTION_STATUS_H
#include "DiagnosticFields.h"
/* Public Network observations; no private proxy/parameter inspection. */
enum {
    APR_CREATE_SEEN=1, APR_CREATE_OK=2,
    APR_START_SEEN=1,
    APR_STATE_REGISTERED=1U<<16, APR_STATE_CALLBACK=1U<<17,
    APR_STATE_CURRENT_ERROR=1U<<18,
    APR_STATE_HISTORY_SHIFT=19,
    APR_REPORT_REQUESTED=1, APR_REPORT_RETURNED=2, APR_REPORT_AVAILABLE=4,
    APR_REPORT_CONFIGURED=8, APR_REPORT_USED=16
};
enum {
    APR_PATH_SEEN=1U<<16, APR_PATH_PRESENT=1U<<17,
    APR_PATH_REASON_API=1U<<18, APR_PATH_WIFI=1U<<19,
    APR_PATH_CELL=1U<<20, APR_PATH_LOOP=1U<<21,
    APR_PATH_EXPENSIVE=1U<<22, APR_PATH_CONSTRAINED=1U<<23,
    APR_PATH_FORCE=1U<<24
};
#endif
